version: '3'
services:
  db:
    hostname: db
    image: postgres:latest
    env_file: ${PWD-.}/config/db.env
    volumes:
      - ./database:/var/lib/mysql:z
      - ${PWD-.}/mysql-db:/docker-entrypoint-initdb.d:z
    restart: unless-stopped
  redis:
    hostname: redis:5
    image: redis:latest
    command: ["redis-server", "--appendonly", "no"]
    volumes:
      - ${PWD-.}/redis:/data:z
    restart: always
  nwserver:
    hostname: nwserver
    stop_signal: SIGINT
    image: nwnxee/unified:latest
    env_file: ${PWD-.}/config/nwserver.env
    links:
      - "redis:redis"
    stdin_open: true
    tty: true
    volumes:
      - ${PWD-.}/logs:/nwn/run/logs.0:z
      - ${PWD-.}/server/:/nwn/home:z
    restart: unless-stopped
    ports:
      - "5121:5121/udp"
    depends_on:
      - influxdb
      - db
      - caddy
  influxdb:
    hostname: influxdb
    image: influxdb:1.7
    restart: unless-stopped
    env_file: ${PWD-.}/config/influxdb.env
    volumes:
    - influxdb:/var/lib/influxdb:z
  grafana:
    hostname: grafana
    image: grafana/grafana:6.0.1
    restart: unless-stopped
    depends_on:
    - influxdb
    env_file: ${PWD-.}/config/grafana.env
    volumes:
    - ./grafana-provisioning:/etc/grafana/provisioning:z
    - grafana:/var/lib/grafana:z
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
  caddy:
    image: caddy:latest
    ports:
      - 80:80
    command: caddy file-server
    volumes:
      - ./caddy/www:/srv:z
      - ./caddy/data:/data:z
      - ./caddy/config:/config:z
volumes:
  influxdb:
  grafana:
